import { createFileRoute } from "@tanstack/react-router";
import { Download, Palette } from "lucide-react";
import { asset } from "../lib/asset";
import { pageScripts } from "../lib/schema";

const SITE = "https://khanakia.com/apps/filemark";

export const Route = createFileRoute("/brand")({
  head: () => {
    const title = "Brand assets — Filemark";
    const desc =
      "Download the Filemark logo, icon, and glyph as SVG and PNG (32–1024px), plus brand colors and product screenshots. Direct links for hotlinking.";
    const url = `${SITE}/brand`;
    return {
      meta: [
        { title },
        { name: "description", content: desc },
        { property: "og:title", content: title },
        { property: "og:description", content: desc },
        { property: "og:url", content: url },
        { name: "twitter:title", content: title },
        { name: "twitter:description", content: desc },
      ],
      links: [{ rel: "canonical", href: url }],
      scripts: pageScripts({
        name: title,
        description: desc,
        url,
        crumbs: [
          { name: "Filemark", url: `${SITE}/` },
          { name: "Brand", url },
        ],
      }),
    };
  },
  component: BrandPage,
});

// PNG sizes generated by `task brand:gen` into public/brand/.
const PNG_SIZES = [32, 64, 128, 256, 512, 1024] as const;

const COLORS = [
  { name: "Ink", hex: "#0A0A0A", note: "Primary / icon background", dark: true },
  { name: "Paper", hex: "#FFFFFF", note: "Foreground on ink", dark: false },
  { name: "Muted", hex: "#717179", note: "Secondary text", dark: true },
];

const SCREENSHOTS = [
  { file: "1-hero.png", label: "Markdown" },
  { file: "2-schema.png", label: "ER diagram" },
  { file: "3-json.png", label: "JSON tree" },
  { file: "4-datagrid.png", label: "Datagrid" },
  { file: "5-tasks-kanban.png", label: "Tasks & Kanban" },
  { file: "promo-tile.png", label: "Promo tile" },
];

function BrandPage(): React.ReactElement {
  return (
    <main className="bg-background text-foreground">
      {/* Hero */}
      <section className="border-b border-border">
        <div className="mx-auto max-w-5xl px-6 py-16 sm:py-20">
          <p className="text-[11px] font-semibold uppercase tracking-[0.16em] text-muted-foreground">
            Press kit
          </p>
          <h1 className="mt-3 text-balance text-[36px] font-semibold leading-[1.05] tracking-tight sm:text-[48px]">
            Brand assets
          </h1>
          <p className="mt-5 max-w-2xl text-balance text-lg leading-relaxed text-muted-foreground">
            The Filemark logo, icon, and glyph in SVG and PNG, plus colors and
            product screenshots. Please don't modify, recolor, or stretch the
            mark — use the files below as-is. MIT project; assets free to use for
            articles, reviews, and integrations.
          </p>
        </div>
      </section>

      {/* App icon */}
      <AssetBlock
        title="App icon"
        desc="The full mark — white file glyph on a rounded ink square. Use this as the primary logo."
        svg="filemark-icon.svg"
        pngBase="filemark-icon"
        previewBg="bg-muted"
      />

      {/* Bare glyph */}
      <AssetBlock
        title="Glyph"
        desc="The file mark with no background (transparent), in ink. For light surfaces or when you need just the symbol."
        svg="filemark-glyph.svg"
        pngBase="filemark-glyph"
        previewBg="bg-foreground"
        previewInvert
      />

      {/* Colors */}
      <section className="border-b border-border">
        <div className="mx-auto max-w-5xl px-6 py-16 sm:py-20">
          <div className="flex items-center gap-2 text-[11px] font-semibold uppercase tracking-[0.16em] text-muted-foreground">
            <Palette size={13} aria-hidden />
            Colors
          </div>
          <h2 className="mt-3 text-[26px] font-semibold tracking-tight sm:text-[32px]">
            Palette
          </h2>
          <div className="mt-8 grid gap-4 sm:grid-cols-3">
            {COLORS.map((c) => (
              <div
                key={c.hex}
                className="overflow-hidden rounded-xl border border-border"
              >
                <div
                  className="h-24 w-full"
                  style={{ backgroundColor: c.hex }}
                />
                <div className="p-4">
                  <div className="text-sm font-medium">{c.name}</div>
                  <div className="mt-0.5 font-mono text-xs text-muted-foreground">
                    {c.hex}
                  </div>
                  <div className="mt-1 text-xs text-muted-foreground">
                    {c.note}
                  </div>
                </div>
              </div>
            ))}
          </div>
        </div>
      </section>

      {/* Screenshots */}
      <section className="border-b border-border">
        <div className="mx-auto max-w-5xl px-6 py-16 sm:py-20">
          <p className="text-[11px] font-semibold uppercase tracking-[0.16em] text-muted-foreground">
            Screenshots
          </p>
          <h2 className="mt-3 text-[26px] font-semibold tracking-tight sm:text-[32px]">
            Product screenshots
          </h2>
          <p className="mt-3 max-w-2xl text-muted-foreground">
            Press-ready captures of every renderer. Click any image to open the
            full-size file.
          </p>
          <div className="mt-8 grid gap-4 sm:grid-cols-2 lg:grid-cols-3">
            {SCREENSHOTS.map((s) => (
              <a
                key={s.file}
                href={asset(`/screenshots/${s.file}`)}
                target="_blank"
                rel="noreferrer"
                className="group overflow-hidden rounded-xl border border-border bg-muted/40 transition-colors hover:border-foreground/30"
              >
                <img
                  src={asset(`/screenshots/${s.file}`)}
                  alt={`Filemark — ${s.label}`}
                  loading="lazy"
                  className="aspect-video w-full object-cover"
                />
                <div className="flex items-center justify-between px-3 py-2 text-xs">
                  <span className="text-muted-foreground">{s.label}</span>
                  <Download
                    size={13}
                    className="text-muted-foreground group-hover:text-foreground"
                    aria-hidden
                  />
                </div>
              </a>
            ))}
          </div>
        </div>
      </section>
    </main>
  );
}

/** A logo variant with light/dark preview + SVG and PNG download links. */
function AssetBlock({
  title,
  desc,
  svg,
  pngBase,
  previewBg,
  previewInvert,
}: {
  title: string;
  desc: string;
  svg: string;
  pngBase: string;
  previewBg: string;
  previewInvert?: boolean;
}) {
  return (
    <section className="border-b border-border">
      <div className="mx-auto max-w-5xl px-6 py-16 sm:py-20">
        <p className="text-[11px] font-semibold uppercase tracking-[0.16em] text-muted-foreground">
          Logo
        </p>
        <h2 className="mt-3 text-[26px] font-semibold tracking-tight sm:text-[32px]">
          {title}
        </h2>
        <p className="mt-3 max-w-2xl text-muted-foreground">{desc}</p>

        <div className="mt-8 grid gap-8 sm:grid-cols-[220px_1fr] sm:items-start">
          <div
            className={`flex aspect-square items-center justify-center rounded-2xl border border-border ${previewBg}`}
          >
            <img
              src={asset(`/brand/${svg}`)}
              alt={`Filemark ${title}`}
              className="size-24"
              // The glyph is ink-colored; invert it so it's visible on the
              // dark preview tile.
              style={previewInvert ? { filter: "invert(1)" } : undefined}
            />
          </div>

          <div className="space-y-6">
            <div>
              <div className="text-[11px] font-medium uppercase tracking-wider text-muted-foreground">
                Vector
              </div>
              <DownloadLink
                href={asset(`/brand/${svg}`)}
                download={svg}
                label="SVG"
                sub="scales to any size"
              />
            </div>

            <div>
              <div className="text-[11px] font-medium uppercase tracking-wider text-muted-foreground">
                PNG
              </div>
              <div className="mt-2 flex flex-wrap gap-2">
                {PNG_SIZES.map((s) => (
                  <a
                    key={s}
                    href={asset(`/brand/${pngBase}-${s}.png`)}
                    download={`${pngBase}-${s}.png`}
                    className="inline-flex h-8 items-center gap-1.5 rounded-md border border-border px-3 text-xs hover:bg-muted"
                  >
                    <Download size={12} aria-hidden />
                    {s}px
                  </a>
                ))}
              </div>
            </div>
          </div>
        </div>
      </div>
    </section>
  );
}

function DownloadLink({
  href,
  download,
  label,
  sub,
}: {
  href: string;
  download: string;
  label: string;
  sub: string;
}) {
  return (
    <a
      href={href}
      download={download}
      className="mt-2 inline-flex h-9 items-center gap-2 rounded-md bg-primary px-4 text-sm font-medium text-primary-foreground hover:opacity-90"
    >
      <Download size={14} aria-hidden />
      {label}
      <span className="text-primary-foreground/70 text-xs font-normal">
        — {sub}
      </span>
    </a>
  );
}
